name: Build and deploy to GitHub Pages

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        run: |
          mkdir -p export/cutscene_code
          cd cutscene_code
          python3 bisdocs.py > ../export/cutscene_code/commands.txt
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./export

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
